import React, { useEffect, useState } from 'react';
import { CalendarDays, Eye, EyeOff, Mail, MapPin, Phone, ShieldCheck, UserRound } from 'lucide-react';
import { adminAPI } from '../../services/api';

export function SettingsNav({ section, navigate }) {
  return <nav className="admin-settings-tabs" aria-label="Settings sections">
    <button className={section==='platform'?'active':''} onClick={()=>navigate('/admin/settings')}>Platform</button>
    <button className={section==='profile'?'active':''} onClick={()=>navigate('/admin/settings/profile')}>Profile</button>
    <button className={section==='security'?'active':''} onClick={()=>navigate('/admin/settings/security')}>Security</button>
  </nav>;
}

const date = value => value ? new Date(value).toLocaleDateString() : '—';

export function AdminProfileOverview({ profile, imageUrl, navigate }) {
  if (!profile) return <div className="admin-empty">Loading profile…</div>;
  const initials=`${profile.first_name?.[0]||''}${profile.last_name?.[0]||''}`||'A';
  return <div className="admin-profile-page">
    <section className="card pad admin-self-hero"><div className="admin-self-avatar large">{imageUrl?<img src={imageUrl} alt="Administrator profile"/>:initials}</div><div><h3>{profile.name}</h3><strong>Administrator</strong><p>{profile.email}</p><span className="admin-status active">{profile.account_status}</span></div><button className="btn btn-primary btn-sm" onClick={()=>navigate('/admin/settings/profile')}>Edit Profile</button></section>
    <div className="admin-grid-2"><section className="card pad"><h3>Personal Information</h3><div className="admin-profile-details"><span><UserRound/>First name<strong>{profile.first_name||'Not provided'}</strong></span><span><UserRound/>Last name<strong>{profile.last_name||'Not provided'}</strong></span><span><Mail/>Email<strong>{profile.email}</strong></span><span><Phone/>Phone<strong>{profile.phone_number||'Not provided'}</strong></span><span className="wide"><MapPin/>Address line 1<strong>{profile.address_line_1||'Not provided'}</strong></span><span className="wide"><MapPin/>Address line 2<strong>{profile.address_line_2||'Not provided'}</strong></span><span><MapPin/>City / Town<strong>{profile.city||'Not provided'}</strong></span><span><MapPin/>State / Region<strong>{profile.state_region||'Not provided'}</strong></span><span><MapPin/>Postal code<strong>{profile.postal_code||'Not provided'}</strong></span><span><MapPin/>Country<strong>{profile.country||'Not provided'}</strong></span></div></section><section className="card pad"><h3>Account Information</h3><dl className="admin-details"><dt>Role</dt><dd>{profile.role}</dd><dt>Joined date</dt><dd>{date(profile.joined_at)}</dd><dt>Account status</dt><dd>{profile.account_status}</dd><dt>Last updated</dt><dd>{date(profile.updated_at)}</dd></dl></section></div>
  </div>;
}

export function AdminProfileForm({ profile, imageUrl, navigate, onSaved }) {
  const [form,setForm]=useState(profile); const [file,setFile]=useState(null); const [preview,setPreview]=useState(imageUrl); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(null);
  useEffect(()=>{setForm(profile);setPreview(imageUrl)},[profile,imageUrl]);
  if(!form)return <div className="admin-empty">Loading profile…</div>;
  const set=key=>e=>setForm(old=>({...old,[key]:e.target.value}));
  const choose=e=>{const next=e.target.files?.[0];if(!next)return;if(next.size>5*1024*1024){setMessage({type:'error',text:'Profile picture must be 5 MB or smaller.'});return}setFile(next);setPreview(URL.createObjectURL(next));};
  const save=async e=>{e.preventDefault();setBusy(true);setMessage(null);try{const keys=['first_name','last_name','phone_number','address_line_1','address_line_2','city','state_region','postal_code','country'];const payload=Object.fromEntries(keys.map(k=>[k,form[k]||null]));const res=await adminAPI.updateProfile(payload);if(file)await adminAPI.uploadProfileImage(file);setFile(null);setMessage({type:'success',text:'Your profile has been updated.'});await onSaved(res.data);}catch(err){setMessage({type:'error',text:err.response?.data?.detail||'Could not save your profile.'})}finally{setBusy(false)}};
  const initials=`${form.first_name?.[0]||''}${form.last_name?.[0]||''}`||'A';
  return <><SettingsNav section="profile" navigate={navigate}/><form className="card pad admin-self-form" onSubmit={save}><h3>Administrator Profile</h3><p>Update your personal and contact information.</p>{message&&<div className={`profile-message ${message.type}`}>{message.text}</div>}<div className="profile-photo-row"><div className="admin-self-avatar">{preview?<img src={preview} alt="Profile preview"/>:initials}</div><div><label className="btn btn-ghost btn-sm">Choose picture<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/></label><small>JPEG, PNG or WebP · maximum 5 MB</small></div></div><div className="profile-grid"><div className="field"><label>First name</label><input value={form.first_name||''} onChange={set('first_name')} required/></div><div className="field"><label>Last name</label><input value={form.last_name||''} onChange={set('last_name')}/></div><div className="field"><label>Email</label><input value={form.email} readOnly/><small>Email changes require verification and are currently disabled.</small></div><div className="field"><label>Phone</label><input value={form.phone_number||''} onChange={set('phone_number')}/></div><div className="field full"><label>Address line 1</label><input value={form.address_line_1||''} onChange={set('address_line_1')}/></div><div className="field full"><label>Address line 2</label><input value={form.address_line_2||''} onChange={set('address_line_2')}/></div><div className="field"><label>City / Town</label><input value={form.city||''} onChange={set('city')}/></div><div className="field"><label>State / Region</label><input value={form.state_region||''} onChange={set('state_region')}/></div><div className="field"><label>Postal code</label><input value={form.postal_code||''} onChange={set('postal_code')}/></div><div className="field"><label>Country</label><input value={form.country||''} onChange={set('country')}/></div></div><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Save Changes'}</button></form></>;
}

export function AdminSecurity({ navigate, onExit }) {
  const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState(null);const [done,setDone]=useState(false);
  const submit=async e=>{e.preventDefault();if(next!==confirm)return setMessage({type:'error',text:'New passwords do not match.'});if(next===current)return setMessage({type:'error',text:'New password must be different from the current password.'});setBusy(true);setMessage(null);try{const res=await adminAPI.changePassword(current,next);setDone(true);setMessage({type:'success',text:res.data.message})}catch(err){setMessage({type:'error',text:err.response?.data?.detail||'Could not change password.'})}finally{setBusy(false)}};
  return <><SettingsNav section="security" navigate={navigate}/><form className="card pad admin-security-form" onSubmit={submit}><ShieldCheck size={30}/><h3>Change Password</h3><p>Use at least 8 characters. You will need to log in again after changing it.</p>{message&&<div className={`profile-message ${message.type}`}>{message.text}</div>}{!done&&<><div className="field"><label>Current password</label><div className="password-input-wrap"><input type={show?'text':'password'} value={current} onChange={e=>setCurrent(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide passwords':'Show passwords'}>{show?<EyeOff/>:<Eye/>}</button></div></div><div className="profile-grid"><div className="field"><label>New password</label><input type={show?'text':'password'} value={next} onChange={e=>setNext(e.target.value)} minLength="8" required/></div><div className="field"><label>Confirm new password</label><input type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} minLength="8" required/></div></div><button className="btn btn-primary" disabled={busy}>{busy?'Changing…':'Change Password'}</button></>}{done&&<button type="button" className="btn btn-primary" onClick={onExit}>Log in again</button>}</form></>;
}
