import React, { useEffect, useState } from 'react';
import { UserRound, ShieldCheck, CircleUserRound } from 'lucide-react';
import { parentAPI } from '../../services/api';

const EMPTY = { first_name:'', last_name:'', email:'', phone_number:'', address_line_1:'', address_line_2:'', city:'', state_region:'', postal_code:'', country:'' };

export default function ParentSettingsScreen({ onNavigate }) {
  const [profile, setProfile] = useState(EMPTY); const [preview, setPreview] = useState(''); const [image, setImage] = useState(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(null);
  useEffect(() => { let objectUrl; Promise.all([parentAPI.getProfile(), parentAPI.getParentProfileImage().catch(() => null)]).then(([res, imageRes]) => { setProfile({ ...EMPTY, ...res.data }); if (imageRes) { objectUrl=URL.createObjectURL(imageRes.data); setPreview(objectUrl); } }).catch(err => setMessage({type:'error',text:err.response?.data?.detail||'Could not load your profile.'})).finally(()=>setLoading(false)); return()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)}; }, []);
  const changeImage=file=>{ setMessage(null); if(!file)return; if(!['image/jpeg','image/png','image/webp'].includes(file.type))return setMessage({type:'error',text:'Choose a JPEG, PNG, or WebP image.'}); if(file.size>5*1024*1024)return setMessage({type:'error',text:'Profile pictures must be 5 MB or smaller.'}); setImage(file); setPreview(URL.createObjectURL(file)); };
  const save=async event=>{ event.preventDefault(); setSaving(true); setMessage(null); try { const {email,role,joined_at,account_status,profile_image_url,...allowed}=profile; const res=await parentAPI.updateProfile(allowed); setProfile({...profile,...res.data}); if(image)await parentAPI.uploadParentProfileImage(image); setImage(null); setMessage({type:'success',text:'Your profile has been updated.'}); } catch(err){setMessage({type:'error',text:err.response?.data?.detail||'Could not save your changes.'})} finally{setSaving(false)} };
  if(loading)return <main className="parent-settings-page"><div className="settings-card">Loading your profile…</div></main>;
  const set=key=>e=>setProfile(p=>({...p,[key]:e.target.value})); const initials=`${profile.first_name?.[0]||''}${profile.last_name?.[0]||''}`||'P';
  return <main className="parent-settings-page"><div className="settings-heading"><button onClick={()=>onNavigate('/parent')}>← Back</button><div><h1>Settings</h1><p>Manage your parent account and profile.</p></div></div><div className="settings-layout">
    <nav className="settings-nav"><a className="active"><UserRound size={17}/> Profile</a><a href="#account"><CircleUserRound size={17}/> Account</a><a href="#security"><ShieldCheck size={17}/> Security</a></nav>
    <div className="settings-content"><form className="settings-card" onSubmit={save}><h2>Parent Profile</h2><p className="settings-muted">Update your personal and contact information.</p>{message&&<div className={`profile-message ${message.type}`}>{message.text}</div>}
      <div className="profile-photo-row"><div className="parent-profile-preview">{preview?<img src={preview} alt="Profile preview"/>:initials}</div><div><label className="btn btn-ghost btn-sm">Choose picture<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>changeImage(e.target.files?.[0])}/></label><small>JPEG, PNG or WebP · maximum 5 MB</small></div></div>
      <div className="profile-grid"><div className="field"><label>First name</label><input value={profile.first_name} onChange={set('first_name')}/></div><div className="field"><label>Last name</label><input value={profile.last_name} onChange={set('last_name')}/></div><div className="field"><label>Email</label><input value={profile.email} readOnly/><small>Email changes require verification and are currently disabled.</small></div><div className="field"><label>Phone number</label><input value={profile.phone_number||''} onChange={set('phone_number')}/></div><div className="field full"><label>Address line 1</label><input value={profile.address_line_1||''} onChange={set('address_line_1')}/></div><div className="field full"><label>Address line 2</label><input value={profile.address_line_2||''} onChange={set('address_line_2')}/></div><div className="field"><label>City / Town</label><input value={profile.city||''} onChange={set('city')}/></div><div className="field"><label>State / Region</label><input value={profile.state_region||''} onChange={set('state_region')}/></div><div className="field"><label>Postal code</label><input value={profile.postal_code||''} onChange={set('postal_code')}/></div><div className="field"><label>Country</label><input value={profile.country||''} onChange={set('country')}/></div></div><button className="btn btn-primary" disabled={saving}>{saving?'Saving…':'Save Changes'}</button>
    </form><section id="account" className="settings-card compact"><h2>Account</h2><dl><dt>Account email</dt><dd>{profile.email}</dd><dt>Role</dt><dd>{profile.role}</dd><dt>Joined</dt><dd>{profile.joined_at?new Date(profile.joined_at).toLocaleDateString():'—'}</dd><dt>Status</dt><dd>{profile.account_status}</dd></dl></section><section id="security" className="settings-card compact"><h2>Security</h2><p>Use the secure reset link sent to your account email to change your password.</p><button className="btn btn-ghost btn-sm" onClick={()=>onNavigate('/forgot-password')}>Reset password</button></section></div>
  </div></main>;
}
